name: ğŸ“¡ Update IP Info

on:
  schedule:
    - cron: "0 * * * *" # Ejecutar cada hora
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Clonar repositorio
        uses: actions/checkout@v3

      - name: ğŸŒ Obtener y actualizar IP
        run: |
          chmod +x update_readme.sh
          ./update_readme.sh

      - name: ğŸš€ Subir cambios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main --rebase
          git add README.md
          git commit -m "ğŸ”„ ActualizaciÃ³n de IP PÃºblica" || echo "Sin cambios que realizar"
          git push origin main || (git pull origin main --rebase && git push origin main)
